spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 09420059474mm
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
